name: "Send Telegram Message"
description: "Send Telegram Message"
author: "Jimmy Sawczuk"
inputs:
  chatID:
    description: "The chat ID to send the message to"
    required: true
  telegramBotURL:
    description: "The URL of the sendMessage endpoint for your bot"
    required: true
  message:
    description: "The message to send"
    required: true
  parseMode:
    description: "The parse mode to use"
    required: false
    default: "HTML"
runs:
  using: "node12"
  main: "dist/main.js"
branding:
  icon: "filter"
  color: "gray-dark"
