name: "Workflow notifier"
description: "Send Telegram messages before, as part of, or after your job."
author: "Jimmy Sawczuk"
inputs:
  chatID:
    description: "The chat ID to send the message to"
    required: true
  telegramBotURL:
    description: "The URL of the sendMessage endpoint for your bot"
    required: true
  commit:
    description: "The Git SHA."
    required: true
  beforeStart:
    description: "Send notification when job starts"
    default: false
  inline:
    description: "Send notification when step is invoked"
    default: false
  afterSuccess:
    description: "Send notification when job completes successfully"
    default: false
  afterError:
    description: "Send notification when job errors"
    default: false

runs:
  using: "node12"
  main: "dist/index.js"
  pre: "dist/index.js"
  post: "dist/index.js"
branding:
  icon: "filter"
  color: "gray-dark"
