name: "Install Hugo"
description: "Install the specified version of Hugo"
author: "Jimmy Sawczuk"
inputs:
  version:
    description: "The version of Hugo to install, i.e. 0.74.3."
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        wget -q https://github.com/gohugoio/hugo/releases/download/v${{ inputs.version }}/hugo_${{ inputs.version }}_Linux-64bit.tar.gz
        tar -xzf hugo_${{ inputs.version }}_Linux-64bit.tar.gz
        sudo cp hugo /usr/local/bin/hugo
branding:
  icon: "filter"
  color: "gray-dark"
