name: "Send Job Failed Message"
description: "Send Telegram Message"
author: "Jimmy Sawczuk"
inputs:
  chatID:
    description: "The chat ID to send the message to"
    required: true
  telegramBotURL:
    description: "The URL of the sendMessage endpoint for your bot"
    required: true
  error:
    description: "Error message (optional)"
    required: false
runs:
  using: "node16"
  main: "dist/main.js"
  post-if: "failure()"
  post: "dist/post.js"
branding:
  icon: "filter"
  color: "gray-dark"
