name: "Get tag from github.ref"
description: "[DEPRECATED] Get the tag from github.ref - use github.ref_name instead"
author: "Jimmy Sawczuk"
inputs:
  ref:
    description: "The ref to clean"
    required: true
outputs:
  tag:
    description: "The tag, if present"
  branch:
    description: "The branch, if present"
runs:
  using: "node24"
  main: "dist/main.js"
branding:
  icon: "filter"
  color: "gray-dark"
